# -*- coding: utf-8 -*-
"""IBNR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs6tm6Ur75bGns688EdVlO7Dan3kkX6B
"""

import streamlit as st
import pandas as pd
import numpy as np
import chainladder as cl
from io import BytesIO

st.set_page_config(page_title="Chain Ladder IBNR Calculator", layout="wide")

# ---------- CUSTOM CSS (African Actuarial Consultants theme) ----------
st.markdown("""
<style>
    /* Global */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }
    /* Header / Navigation */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        border-bottom: 3px solid #D4AF37;
    }
    .logo {
        color: #D4AF37;
        font-size: 1.8rem;
        font-weight: bold;
        text-decoration: none;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
        transition: color 0.3s;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }
    /* Hero Section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }
    /* Main container */
    .main-container {
        max-width: 1400px;
        margin: 2rem auto;
        padding: 0 2rem;
    }
    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        margin-top: 0;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }
    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }
    /* Streamlit element overrides */
    .stButton > button, .stDownloadButton > button {
        background-color: #D4AF37;
        color: #000000;
        border: none;
        border-radius: 4px;
        font-weight: bold;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton > button:hover, .stDownloadButton > button:hover {
        background-color: #B8960F;
        color: #FFFFFF;
    }
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 5px;
        padding: 1rem;
    }
    .stMultiSelect [data-baseweb="select"] {
        border: 1px solid #D4AF37;
        border-radius: 4px;
    }
    .dataframe {
        border: 1px solid #D4AF37;
        border-radius: 8px;
        overflow: hidden;
    }
</style>
""", unsafe_allow_html=True)

# ---------- Header ----------
st.markdown("""
<div class="header">
    <a href="#" class="logo">AAC</a>
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Chain Ladder IBNR Calculator</h1>
    <p>Upload your claims data (CSV). Select the currency columns for which you want the Results for. The app will compute IBNR and Ultimate claims by product using the Chain Ladder method.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Container ----------
st.markdown('<div class="main-container">', unsafe_allow_html=True)

# File uploader
uploaded_file = st.file_uploader("Upload a CSV file with loss data", type="csv")

if uploaded_file is not None:
    try:
        # Handle encoding
        try:
            df = pd.read_csv(uploaded_file, encoding='utf-8')
        except UnicodeDecodeError:
            uploaded_file.seek(0)
            df = pd.read_csv(uploaded_file, encoding='cp1252')
            st.warning("File read with Windows‑1252 encoding. For best results, save your CSV as UTF‑8.")

        # Display raw data head
        with st.expander("Preview of the uploaded data"):
            st.dataframe(df.head())

        # Check required columns
        required = ['Loss_Date', 'Report_Date', 'Product']
        missing = [col for col in required if col not in df.columns]
        if missing:
            st.error(f"Missing required columns: {', '.join(missing)}. Please ensure your CSV contains Loss_Date, Report_Date, and Product.")
        else:
            # Convert dates
            df['Loss_Date'] = pd.to_datetime(df['Loss_Date'], errors='coerce')
            df['Report_Date'] = pd.to_datetime(df['Report_Date'], errors='coerce')
            if df['Loss_Date'].isna().any() or df['Report_Date'].isna().any():
                st.error("Some dates could not be parsed. Please check your date columns.")
                st.stop()

            # Identify numeric columns (excluding date and product columns)
            numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
            # Also include any object columns that might be numeric but stored as strings? We'll let user choose anyway.
            # Better: list all columns and let user pick, but we'll show only numeric.
            # Also remove Product from numeric list if it's numeric (maybe it's integer)
            if 'Product' in numeric_cols:
                numeric_cols.remove('Product')
            if 'Loss_Date' in numeric_cols:
                numeric_cols.remove('Loss_Date')
            if 'Report_Date' in numeric_cols:
                numeric_cols.remove('Report_Date')

            if not numeric_cols:
                st.error("No numeric columns found in the data. Please ensure you have numeric columns for claim amounts.")
                st.stop()

            # Multi-select for currency columns
            st.markdown("### Select Currency Columns (Claim Amounts)")
            selected_columns = st.multiselect(
                "Choose the columns that contain claim amounts for IBNR Aggregation (these will be used as 'columns' in the triangle):",
                options=numeric_cols,
                default=numeric_cols[:min(3, len(numeric_cols))]  # default first few
            )

            if not selected_columns:
                st.warning("Please select at least one currency column to proceed.")
                st.stop()

            # Grouping column (Product) – we assume it's 'Product'
            index_col = 'Product'

            # Create triangle
            try:
                triangle = cl.Triangle(
                    data=df,
                    origin='Loss_Date',
                    development='Report_Date',
                    columns=selected_columns,
                    index=index_col,
                    cumulative=False  # assume incremental data; adjust if cumulative
                )
            except Exception as e:
                st.error(f"Error creating triangle: {e}")
                st.stop()

            # Fit Chain Ladder model
            try:
                model = cl.Chainladder().fit(triangle)
            except Exception as e:
                st.error(f"Error fitting Chain Ladder model: {e}")
                st.stop()

            # Extract IBNR and Ultimate
            ibnr = model.ibnr_
            ultimate = model.ultimate_

            # Convert to DataFrame and group by Product (index level)
            ibnr_df = ibnr.to_frame()
            ultimate_df = ultimate.to_frame()

            # Group by the index (Product) – note: after to_frame, the index is MultiIndex (Product, origin, etc.)
            # We need to sum over the selected columns. The DataFrame has columns = selected_columns, and index is MultiIndex with 'Product' as one level.
            # Let's reset index and group by Product.
            ibnr_reset = ibnr_df.reset_index()
            ultimate_reset = ultimate_df.reset_index()

            # Group by 'Product' (level name) and sum the selected columns
            # Ensure 'Product' is a column after reset
            ibnr_summary = ibnr_reset.groupby('Product')[selected_columns].sum().reset_index()
            ultimate_summary = ultimate_reset.groupby('Product')[selected_columns].sum().reset_index()

            # Display results
            col1, col2 = st.columns(2)
            with col1:
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.subheader("📈 IBNR by Product")
                st.dataframe(ibnr_summary, use_container_width=True)
                st.markdown('</div>', unsafe_allow_html=True)

            with col2:
                st.markdown('<div class="card">', unsafe_allow_html=True)
                st.subheader("📊 Ultimate Claims by Product")
                st.dataframe(ultimate_summary, use_container_width=True)
                st.markdown('</div>', unsafe_allow_html=True)

            # Prepare Excel downloads
            output_ibnr = BytesIO()
            with pd.ExcelWriter(output_ibnr, engine='openpyxl') as writer:
                ibnr_summary.to_excel(writer, index=False, sheet_name='IBNR')
            output_ibnr.seek(0)

            output_ultimate = BytesIO()
            with pd.ExcelWriter(output_ultimate, engine='openpyxl') as writer:
                ultimate_summary.to_excel(writer, index=False, sheet_name='Ultimate')
            output_ultimate.seek(0)

            # Download buttons
            st.markdown("### Download Results")
            dcol1, dcol2 = st.columns(2)
            with dcol1:
                st.download_button(
                    label="Download IBNR Summary (Excel)",
                    data=output_ibnr,
                    file_name="ibnr_summary.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )
            with dcol2:
                st.download_button(
                    label="Download Ultimate Summary (Excel)",
                    data=output_ultimate,
                    file_name="ultimate_summary.xlsx",
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                )

    except Exception as e:
        st.error(f"An unexpected error occurred: {e}")

st.markdown('</div>', unsafe_allow_html=True)  # close main-container

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved. | <a href="#">Privacy</a> | <a href="#">Terms</a></p>
    <p style="margin-top: 0.5rem; font-size: 0.9rem;">Powered by Vanababa</p>
</div>
""", unsafe_allow_html=True)